### ISSUE TITLE
PullRequestu v GitHubu dát k dispozici proklik na konkrétní sestavení

### ISSUE THREAD

**Issue by AloisJasa** [peckadesign/CIServer#3]
Aktuálně se v GitHubu v PR dá prokliknout do CIServeru na dashboard.

Odkaz bych upravil, aby se dalo prokliknout na konkrétní sestavení.

**Comment by MilanPala** [comment]
Odkaz pod textem `Details` směřuje v případě úspěchu na testovací server, v opačných případech na CI server. Aby vždy ukazoval na CI server by museli projekťáci schválit, že jim nevadí se dostat na  CI server a z něj prokliknout na testovací server.

Odkaz vlevo pod logem měnit nejde. Je nastavený globálně pro všechny statusy.

**Comment by AloisJasa** [comment]
Edit: Po konzultaci se rozhodlo, že zatím bude stačit přehled/grid všech aktivních sestavení (s rozumným filtrem) v administraci CIServeru především pro to, že zalogované informace využijí hlavně jen programátoři.
Mezikrokem, který z GitHubu prvně přesměruje na detaily sestavení v CIServeru a pak až na testovací server, nebudeme ostatní zatěžovat.

**Comment by MilanPala** [comment]
Pokud bys chtěl dávat grid, tak Nextras má grid v sobě.

**Comment by MilanPala** [comment]
Víťa řeší Nextras vs. Ublaboo: https://github.com/peckadesign/pdproject5/issues/920

**Comment by MilanPala** [comment]
V masteru.

**Comment by MilanPala** [comment]
NO. Díky moc za spolupráci.
