### ISSUE TITLE
Testy se spouštějí dvakrát po sobě

### ISSUE THREAD

**Issue by milous** [peckadesign/CIServer#8]
<img width="789" alt="snimek obrazovky 2017-06-09 v 9 54 57" src="https://user-images.githubusercontent.com/16692814/26966295-cadaf8b4-4cf9-11e7-8ccb-68b8672214f4.png">
<img width="804" alt="snimek obrazovky 2017-06-09 v 9 54 39" src="https://user-images.githubusercontent.com/16692814/26966296-cae1d4b8-4cf9-11e7-83c2-5b2bd93ecf1e.png">

**Comment by MilanPala** [comment]
Vyřešeno, byly chybně napojené hooky.
